src/Entity/Email.php
<?php

namespace App\Entity;

use App\Entity\Newsletter\Categories;
use App\Repository\EmailRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=EmailRepository::class)
 * @UniqueEntity(fields={"email"}, message="email existant ")
 */
class Email
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\ManyToMany(targetEntity=Categories::class, inversedBy="emails")
     */
    private $Categories;

    public function __construct()
    {
        $this->Categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection<int, Categories>
     */
    public function getCategories(): Collection
    {
        return $this->Categories;
    }

    public function addCategory(Categories $category): self
    {
        if (!$this->Categories->contains($category)) {
            $this->Categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Categories $category): self
    {
        $this->Categories->removeElement($category);

        return $this;
    }

}

templates/components/_changepassword.html.twig
{% extends "base2.html.twig" %}
{% block body %}


		<div class="container d-flex align-items-center  " style="height: 100vh;">
            <div class=" col-md-6">
            {% for message in app.flashes('ch_success') %}
              <div class="alert alert-success text-center">{{ message }}</div>
            {% endfor %}
                {% for message in app.flashes('ch_erro') %}
              <div class="alert alert-danger text-center">{{ message }}</div>
            {% endfor %}
                {{form_start(form)}}
                    {{form_row(form.plainPassword)}}
                      <button class="btn banner-btn shadow mt-2" type="submit">
						<span>
							Enregistrer
						</span>
					</button>
              {{form_end(form)}}
              
                  
            </div>
		</div>

{% endblock %}

templates/components/_forget.html.twig
<h1>Mot de passe oublié </h1>

<p>Renitialisé votre mot de passe en cliquer sur ce lien </p>

<a href=" {{ absolute_url(path('app.forget.password',{token: token })) }} "> clique me </a>

templates/components/_forgetemail.html.twig
{% extends "base2.html.twig" %}

{% block body %}

		<div class="container d-flex align-items-center  " style="height: 100vh;">

            <div class=" col-md-6">
              {% for message in app.flashes('forget_email') %}
              <div class="alert alert-success text-center">{{ message }}</div>
            {% endfor %}
                {% for message in app.flashes('forget') %}
              <div class="alert alert-danger text-center">{{ message }}</div>
            {% endfor %}
            <h2>Mot de passe oublié </h2>
            <br>
                {{form_start(form)}}
                    {{form_row(form.email)}}
                      <button class="btn banner-btn shadow mt-2" type="submit">
						<span>
							envoyé
						</span>
					</button>
              {{form_end(form)}}
              
                  
            </div>
		</div>

{% endblock %}

templates/components/_link.html.twig
<div class="d-flex mt-2 justify-content-center">
  <div class="">
    <a href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwji9rrKzpTyAhWxgVwKHQuJCy4QFjAAegQIBxAD&url=https%3A%2F%2Fwww.facebook.com%2FLadatema.Research.Sarl%2F&usg=AOvVaw1tNlNZux8RILtQzE8km5wz" target="_blank" class="btn-social shadow  "> <i class="fab fa-facebook-f "></i></a>
    <a href="https://www.linkedin.com/in/ladatema-research-838a02106/" target="_blank" class="btn-social shadow  "> <i class="fab fa-linkedin-in"></i></a>
    <a href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwip9-XDz5TyAhWUgVwKHRZ5B6kQFjAAegQIBxAD&url=https%3A%2F%2Ftwitter.com%2Fladatemaresearc%3Flang%3Den&usg=AOvVaw3MxvUFOLWKsFcRXehBldRs" target="_blank" class="btn-social shadow "><i class="fab fa-twitter"></i></a>
  </div>
</div>

templates/components/_newsemail.html.twig
<h1>{{ news.Titre }} </h1>

<p>{{news.contenu |raw  }} </p>

<a href=" {{ absolute_url(path('home')) }} "> Ladatema Research </a>

templates/components/_offre.html.twig
	<h2 class="text-center p-2 p-lg-3  ">Les dernières offres d'emploi</h1>
<div class="offre-content">

    {% for offre in offres %}
        <div class=" banner-info transcale p-0 shadow">
            {% if offre.image %}
                <div class="banner-img2">
                    <img src="{{ vich_uploader_asset(offre, 'imageFile') }}"/>
                </div>
            {% else %}
                <div class="banner-img2">
                    <img class="img-fluid w-50" src="{{ asset('assets/img/logo/logo.png') }}"/>
                </div>
            {% endif %}
            <div class="offre-data">
                <div class="offre-title"  style="">
                   <span class="badge badge-danger" style="background: var(--secondary-color) !important ;">
                      {{ offre.nombreposte }}
                    </span>
                    {{ offre.Titre | capitalize }}
                </div>
                <div class="d-flex justify-content-center">
                <div class="data">
                <div class="">
                  {% if offre.recruteur  %}
                    <div class=""style="font-weight: bold ;">
                      <span > <i class="fas fa-synagogue"></i> Organisation  </span>
                      <span> {{ offre.recruteur.nomemtreprise | capitalize }}</span>
                    </div>
                  {% endif %}

                    <div class="">
                      <span> <i class="fas fa-user-graduate"></i>  Niveau d'etude  </span>
                      <span> {{ offre.etude | capitalize }}</span>
                    </div>
                    <div class="">
                      <span> <i class="fas fa-flask"></i>   Expérience  </span>
                      <span> {{ offre.experience | capitalize }}</span>
                    </div>

                    <div class="">
                      <span>   <i class="fas fa-flag"></i>  Ville  </span>
                      <span> {{ offre.ville | capitalize }}</span>
                    </div>

                    <div class="">
                      <span> <i class="far fa-calendar-times"></i>   Expiration  </span>
                      <span> {{ offre.delai | date('d/m/y') }}</span>
                    </div>
                    <div class="">
                      <span><i class="far fa-clock"></i>   Publier le  </span>
                      <span> {{ offre.updateat | date('d/m/y')}}</span>
                    </div>
                  </div>
                </div>
                </div>
                <div class=" offre-link ">
                    <a href="{{ path('une_offre',{'titre': offre.Titre | replace({'/': "-", ' ': "-"}) ,'id': offre.id  })  }} " class="">Lire plus
                    </a>

                </div>

            </div>
        </div>
    {% endfor %}
</div>

templates/components/_postuleEmails.html.twig
<h1> {{object }}  </h1>

<p>{{ message }} </p>

{% for key , value in allfile  %}
    <a href=" {{ absolute_url( asset('assets/file/' ~ value ) ) }} "> Télécharger  mon fichier   </a> <br>
{% endfor %}

templates/components/_profil.html.twig
<h2 class="text-center p-2 p-lg-3  "> Profils récents</h1>
<div  class="offre-content">
  {% for candidat in candidats %}
					<div class=" banner-info col-md-12 transcale  p-0 shadow">
						<div class="cv-img">
							<img src="assets/users/profil/{{ candidat.avatar.filename }}" alt="">
						</div>
						<div class="cv-name">
							<div> {{ candidat.nom | upper }}  {{ candidat.prenom | capitalize }}</div>
						</div>
						<div class="data p-3">
							
							<div class="">
							<div class="">
								<span> <i class="fas fa-user-graduate"></i>  Niveau d'etude  </span>
								<span> {{ candidat.niveau | capitalize }}</span>
                   			 </div>
							  <div class="">
								<span> <i class="fas fa-flask"></i>   Expérience  </span>
								<span> {{ candidat.anexp | capitalize }}</span>
                   			 </div>
							 <div class="">
								<span> <i class="fas fa-user-graduate"></i>  Métier  </span>
								<span> {{ candidat.metier | capitalize }}</span>
                   			 </div>
							 <div class="">
								<span> <i class="fas fa-user-graduate"></i>  Pays  </span>
								<span> {{ candidat.pays | capitalize }}</span>
                   			 </div>
							</div>
						</div>

						<div class="cv-link">
							<a href="{{ path('un_cv',{email: candidat.email}) }}">Profil</a>
						</div>
					</div>
				{% endfor %}
</div>

templates/components/_stats.html.twig
	<section id="section2" class="jumbotron brounded-0 gradient" >
		<div class=" row justify-content-center ">
			<div class="text-center text-light col-md-2 ">
				<div class="icon">
					<i class="fa fa-building fa-3x  p-3"></i>
				</div>
				<div class="">
					<h2 class=" counter" >{{ countentreprise.count }}</h2>
					<h4 class=" ">Entreprises</h4>
				</div>
			</div>
			<div class="text-center text-light col-md-2 ">
				<div class="icon">
					<i class="fa fa-folder fa-3x p-3 "></i>
				</div>
				<div class="">
					<h2 class=" counter" >{{ countoffre.count }}</h2>
					<h4 class=" ">Offres d'emploi</h4>
				</div>
			</div>
			<div class="text-center text-light col-md-2 ">
				<div class="icon">
					<i class="fa fa-file fa-3x p-3"></i>
				</div>
				<div class="">
					<h2 class=" counter" >10<h2>
					<h4 class=" ">Cv</h4>


				</div>
			</div>
			<div class="text-center text-light col-md-2">
				<div class="icon">
					<i class="fa fa-users fa-3x p-3"></i>
				</div>
				<div class="">
					<h2 class=" counter" >50</h2>
					<h4 class=" ">Utilisateurs</h4>
				</div>
			</div>
		</div>
	</section>

templates/components/inscription.html.twig
<section class=" p-3 gradient">
  <div class="container">
    <div class="row align-items-center justify-content-center p-lg-5 p-md-2">
      <div class="col-lg-8 justify-content-center text-white">
        <h2 class="text-center">
       À LA RECHERCHE D'UN EMPLOI 
        </h2>
        <p class="text-center d-block  text-light pt-3 " style="font-weight: normal ">Comme plus de 100.000 personnes inscrites sur cDiscussion.com, inscrivez vous pour recevoir chaque jour des dizaines d'offres d'emploi et candidatez gratuitement en quelques clics!</p>

        <p></p>
        <div class="d-flex flex-wrap">
          <a href="{{ path("app_register_candidat")}}" class="banner-btn2 btn-success btn shadow" style="background-color: #28a745;">Inscription du candidat</a>
          <a href="{{ path("app_register_recruteur")}}" class="banner-btn2 btn text-dark  shadow" style="background-color: #ffc107;" >Inscription du Recruteur</a>
        </div>
      </div>
    </div>
  </div>
</section>

templates/components/loader.html.twig
<div class="loader">
    {# <div class="loader-logo">
        <span class="letter">L</span>
        <span class="letter">A</span>
        <span class="letter">D</span>
        <span class="letter">A</span>
        <span class="letter">T</span>
        <span class="letter">E</span>
        <span class="letter">M</span>
        <span class="letter">A</span>
        <span class="letter">.</span>
        <span class="letter">.</span>
        <span class="letter">.</span>
    </div> #}

    <img alt="Ladatema Loader animation" src="{{asset('assets/Eclipse-1s-200px.svg')}}" title="Ldatema research">
</div>

templates/components/newsletter.html.twig
<section class="p-lg-5 p-3 gradient">
	<div class="container">
		<div class="row align-items-center p-lg-5 p-md-2">
			<div class="col-lg-6 text-white">
				<small>Newsletter</small>
				<h2>
					Ladatema Plus proche de vous
				</h2>
				<p class="mt-lg-4 mb-lg-4 my-1">
					Vous êtes prêt ? Abonnez-vous pour être aux premières pages des
															          informations
				</p>
				
				<div class="flex flex-row  " >
				   {% for message in app.flashes('newsletter') %}
              <div class="alert alert-success text-center">{{ message }}</div>
            {% endfor %}
                {{form_start(news_form)}}
					{{form_row(news_form.email )}}
					<button type="button" class="btn btn-primary my-3" data-toggle="modal" data-target="#newsletter">Abonnez-vous</button>


					<div class="modal text-dark fade" id="newsletter" tabindex="-1" role="dialog" aria-labelledby="newsletterLabel" aria-hidden="true">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title" id="exampleModalLabel">Selectionnez vos newsletter </h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body text-dark ">
                                    
                                    {{form_widget(news_form.categories)}}

									<button type="submit" class="btn btn-primary my-3">Abonnez-vous</button>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn  btn-sm btn-danger" data-dismiss="modal">fermer</button</div>
								</div>
							</div>
						</div>
					</div>
                {{form_end(news_form )}}
				</div>
				
			</div>
			<div class="col-lg">
				<img class="img-fluid shadow" src="{{ asset('assets/img/pexels-ketut-subiyanto-4559759.jpg') }}"/>
			</div>
		</div>
	</div>
</section>

templates/components/secteur.html.twig
{% for secteur in secteurs  %}
<div class=" item text-center shadow-sm " >
    <div class="banner-secteur-icon"> ICON</div>
    <div class="banner-secteur-bg  bg-primary text-white" >
        <h6 class="">{{ secteur.nom }}</h6>
        <p class="card-text">
            {%  set count =0  %}
            {% for offres in secteur.offres %}
                {% set count= count + 1 %}
            {% endfor %}
            ({{ count }})
        </p>
    </div>
</div>
{% endfor %}